### ISSUE TITLE
Error in opening cutscene

### ISSUE THREAD

**Issue by astra-the-boop** [astra-the-boop/second-chance-game#1]
Seems to be an error with the sketchAnimate function

Happens right after starting the game (after the title screen)

```Traceback (most recent call last):
  File "C:\Users\Student\Downloads\second-chance-game-main\second-chance-game-main\main.py", line 121, in <module>
    sketchAnimate(0.3, "frame1", "frame2", "frame3", 3)
  File "C:\Users\Student\Downloads\second-chance-game-main\second-chance-game-main\main.py", line 26, in sketchAnimate
    for i in cycle:
TypeError: 'int' object is not iterable

Process finished with exit code 1```

**Comment by astra-the-boop** [comment]
Fixed. Error was caused by typo on line 26:

Initial code: 
```def sketchAnimate(delay, f1, f2, f3, cycle):
    for i in cycle:
```

Fixed code:
```def sketchAnimate(delay, f1, f2, f3, cycle):
    for i in range(cycle):
```
